#!/bin/bash

set +e
set -v

db2 drop db sandbox
db2stop

set -e
db2start 

db2 -x "change isolation to ur"

db2 -x "CREATE DATABASE SANDBOX
 AUTOMATIC STORAGE YES 
 USING CODESET UTF-8 TERRITORY US COLLATE USING SYSTEM PAGESIZE 4096
 RESTRICTIVE"

db2 -x "CONNECT TO SANDBOX"
db2 -x "AUTOCONFIGURE USING
 mem_percent 2
 Workload_type mixed
 num_stmts 25
 admin_priority both
 num_local_apps 16
 num_remote_apps 128
 isolation CS
 APPLY DB only"

db2 -x "CREATE BUFFERPOOL USER4K01D   SIZE 16384 PAGESIZE  4 K"
db2 -x "CREATE BUFFERPOOL USER4K01I   SIZE  8192 PAGESIZE  4 K"
db2 -x "CREATE BUFFERPOOL TOOLS32K01D SIZE   250 PAGESIZE 32 K"
db2 -x "CREATE BUFFERPOOL STEMP4K01D  SIZE  1024 PAGESIZE  4 K"
db2 -x "CREATE BUFFERPOOL STEMP8K01D  SIZE   250 PAGESIZE  8 K"
db2 -x "CREATE BUFFERPOOL STEMP32K01D SIZE   250 PAGESIZE 32 K"
db2 -x "ALTER  BUFFERPOOL IBMDEFAULTBP IMMEDIATE SIZE 2048"

db2 -x "CONNECT RESET"

db2 -x "CONNECT TO SANDBOX"

db2 -x "RENAME TABLESPACE USERSPACE1  TO USER4K01D"
db2 -x "RENAME TABLESPACE TEMPSPACE1  TO STEMP4K01D"

db2 -x "CREATE      TABLESPACE USER4K01I PAGESIZE 4K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 32 OVERHEAD 8.5 PREFETCHSIZE 192 TRANSFERRATE 0.04 BUFFERPOOL USER4K01I"
db2 -x "CREATE      TABLESPACE USER32K01I PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 32 OVERHEAD 8.5 PREFETCHSIZE 192 TRANSFERRATE 0.04 BUFFERPOOL TOOLS32K01D"
db2 -x "CREATE LONG TABLESPACE USER4K01L PAGESIZE 4K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 32 OVERHEAD 8.5 PREFETCHSIZE 192 TRANSFERRATE 0.04 BUFFERPOOL USER4K01D"

db2 -x "CREATE  SYSTEM TEMPORARY  TABLESPACE STEMP8KD PAGESIZE 8 K  MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 32 OVERHEAD 8.5 PREFETCHSIZE 192 TRANSFERRATE 0.04 BUFFERPOOL  STEMP8K01D"

db2 -x "CREATE  SYSTEM TEMPORARY  TABLESPACE STEMP32KD PAGESIZE 32 K  MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 32 OVERHEAD 8.5 PREFETCHSIZE 192 TRANSFERRATE 0.04 BUFFERPOOL  STEMP32K01D"


db2 -x "ALTER TABLESPACE USER4K01D  BUFFERPOOL USER4K01D"
db2 -x "ALTER TABLESPACE STEMP4K01D BUFFERPOOL STEMP4K01D"

#-- Disable file system caching (double buffering) let DB2 bufferpools handle this
db2 -x "ALTER TABLESPACE USER4K01D NO FILE SYSTEM CACHING DROPPED TABLE RECOVERY ON AUTORESIZE YES INCREASESIZE 10 PERCENT"
db2 -x "ALTER TABLESPACE USER4K01I NO FILE SYSTEM CACHING DROPPED TABLE RECOVERY ON AUTORESIZE YES INCREASESIZE 10 PERCENT"
db2 -x "ALTER TABLESPACE USER4K01L NO FILE SYSTEM CACHING DROPPED TABLE RECOVERY ON AUTORESIZE YES INCREASESIZE 10 PERCENT"

#--------------------------------------------------------
#-- Database configuration parameters
#--------------------------------------------------------
# db2 -x "UPDATE DB CFG FOR SANDBOX USING locklist 4096"
# db2 -x "UPDATE DB CFG FOR SANDBOX USING maxlocks 90"
db2 -x "UPDATE DB CFG FOR SANDBOX USING avg_appls 2"
db2 -x "UPDATE DB CFG FOR SANDBOX USING stmtheap 4096"
db2 -x "UPDATE DB CFG FOR SANDBOX USING dft_queryopt 5"
db2 -x "UPDATE DB CFG FOR SANDBOX USING UTIL_HEAP_SZ 16384"

set +e
db2 -x "UPDATE DB CFG FOR SANDBOX USING LOCKTIMEOUT 55"
db2 -x "UPDATE DB CFG FOR SANDBOX USING TRACKMOD  ON"
db2 -x "UPDATE DB CFG FOR SANDBOX USING LOGFILSIZ 8192"
db2 -x "UPDATE DB CFG FOR SANDBOX USING LOGPRIMARY 16"
db2 -x "UPDATE DB CFG FOR SANDBOX USING LOGSECOND  16"
db2 -x "UPDATE DB CFG FOR SANDBOX USING LOGBUFSZ 128 IMMEDIATE"
set -e 

# Enable auto maintenance
db2 -x "UPDATE DB CFG FOR SANDBOX USING AUTO_MAINT ON"
db2 -x "UPDATE DB CFG FOR SANDBOX USING AUTO_TBL_MAINT ON"
db2 -x "UPDATE DB CFG FOR SANDBOX USING AUTO_RUNSTATS ON"
# db2 -x "UPDATE DB CFG FOR SANDBOX USING LOGARCHMETH1 DISK:/db2work"
# db2 -x "UPDATE DB CFG FOR SANDBOX USING LOGARCHMETH1 TSM"

# At this point a database backup is mandatory, before a connection is allowed.
db2 -x "BACKUP DB SANDBOX TO /dev/null"

db2 terminate
exit 


